queue_rules:
  - name: default
    conditions: []

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - "check-success=ci/circleci: build"
    actions:
      queue:
        name: default